### ISSUE TITLE
Cannot compile it

### ISSUE THREAD

**Issue by zhum** [Heaven31415/CrystalSpaceShooter#2]
If I run `./build.sh` I get this:
```
Error in ./src/main.cr:1: while requiring "./game"

require "./game"
^

in ./src/game.cr:1: while requiring "./audio"

require "./audio"
^

in ./src/audio.cr:1: while requiring "./resources"

require "./resources"
^

in ./src/resources.cr:6: while requiring "./packed_resources"

require "./packed_resources"
^

in ./src/packed_resources.cr:1: while requiring "crsfml/graphics": can't find file 'crsfml/graphics' relative to '/home/serg/CrystalSpaceShooter/src'

require "crsfml/graphics"
^

```

**Comment by Heaven31415** [comment]
Hey, thanks for trying to build the game. I think I will need more information to help you. 

Can you tell me which version of crystal compiler are you using? You can get this information by typing `crystal --version` (if you have crystal compiler available in your path) in your CLI. I will also need to know what operating system you are using.

There is also one big caveat. Right now this game will work out of the box only on a few Linux distributions, but it will be a pain to install it on anything else. I could fix this, but I'm not planning to, because it's connected to the CrSFML library which I'm right now using to develop this game. 

I'm not planning to fix this, because I'm working on my own library and when I'm done, I'm gonna use it instead of CrSFML and then I will give proper instructions on how to install this game on every supported platform.

If you want I will be glad to send you a message (or email) when this happens (I'm working on it right now as fast as I can, so I think it will happen in the nearest future).

**Comment by Heaven31415** [comment]
Your Crystal complier is definitely too old (recent version is 0.26.0) and because of that you have old require lookup rules which means that it won't work correctly with actual structure of the project. 

Upgrading your compiler should fix the problem.

I hope that I'll finish my library too :P For the moment you can use this instead: https://github.com/oprypin/crsfml which is really good, but it's a little bit difficult to setup if you want to share it across platforms.

**Comment by zhum** [comment]
OK! Version 0.26.1 works fine.

I've noticed only one strange thing - after death, you still can shoot, but you're invisible :)
